language: php
matrix:
    include:
        - php: 5.6
        - php: 7.0
sudo: false
dist: trusty
install:
- composer install
script: phpunit --fail-on-warning --configuration phpunit.xml --coverage-text
warnings_are_errors: true